"""empty message

Revision ID: ca4372811450
Revises: 
Create Date: 2018-07-14 16:14:41.283600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4372811450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('list_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_email'), 'import', ['email'], unique=False)
    op.create_index(op.f('ix_import_timestamp'), 'import', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_timestamp'), table_name='import')
    op.drop_index(op.f('ix_import_email'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
